### ISSUE TITLE
Stretta Aleatoric no longer works

### ISSUE THREAD

**Issue by fotisandstuff** [stretta/Stretta-Inspiration-Tools#1]
Hello! I'm a big fan of Stretta Aleatoric. Unfortunately, it doesn't seem to work on Live 10.1.4. I use Win 10. The last version I could use Aleatoric in was, I think, 10.0.6.

**Comment by stretta** [comment]
have you tried satori aleatoric in the satori repository?

**Comment by fotisandstuff** [comment]
> have you tried satori aleatoric in the satori repository?

Oh, my God! I had no idea Satori is an improved version of Stretta Tools. Yes, it works! Thank you!
